/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `wp_terms` VALUES
(1,"Uncategorized","uncategorized",0),
(2,"Startups","startups",0),
(3,"Travel","travel",0),
(4,"acceptance","acceptance",0),
(5,"acuteness","acuteness",0),
(6,"advantages","advantages",0),
(7,"appearance","appearance",0),
(8,"Castle","castle",0),
(9,"children","children",0),
(10,"county","county",0),
(11,"everything","everything",0),
(12,"felicity","felicity",0),
(13,"guide","guide",0),
(14,"marked","marked",0),
(15,"mistaken","mistaken",0),
(16,"mistress","mistress",0),
(17,"moment","moment",0),
(18,"perfectly","perfectly",0),
(19,"Photography","photography",0),
(20,"september","september",0),
(21,"Stories","stories",0),
(22,"stronger","stronger",0),
(23,"suffer","suffer",0),
(24,"suspicion","suspicion",0),
(25,"thoroughly","thoroughly",0),
(26,"twenty","twenty",0),
(27,"unlocked","unlocked",0),
(28,"unpacked","unpacked",0),
(29,"Default Top Menu","default-top-menu",0),
(30,"Footer menu","footer-menu",0),
(31,"Main menu","main-menu",0);
